---
# tasks file for ansible-role-nginx-controller-gateway

- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  with_items:
    - controller_fqdn
    - environment_name
    - controller_auth_token
    - gateway.name
    - ingress.uris
    - ingress.placement.instanceRefs

- name: Build JSON payload
  template: src=gateway.j2 dest=gateway.json

- name: form the gateway url
  set_fact:
    gateway_url: "https://{{controller_fqdn}}/{{api_version}}/services/environments/{{environment_name}}/gateways/{{gateway.name}}"

- name: upsert gateway (create if absent, change if present)
  uri:
    url: "{{ gateway_url }}"
    method: "PUT"
    body: "{{(lookup('file','gateway.json'))}}"
    body_format: json
    status_code:
    - 200
    - 201
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{controller_auth_token}}"
  register: gateway_status

- name: show gateway create status
  debug: 
    msg: "{{ gateway_status }}"

# pause to give the system a moment to initiate the change
- name: pause
  pause:
   seconds: 2

- name: Confirm component is provisioned and not errored
  uri:
    url: "{{ gateway_url }}"
    method: "GET"
    body_format: json
    status_code:
    - 200
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ controller_auth_token }}"
  register: gateway_current_status
  until: ( gateway_current_status is defined ) and
         ( gateway_current_status.json.currentStatus.state.selfConfigState.isConfiguring != True )
  retries: 50
  delay: 2
  failed_when: ( gateway_current_status.json.currentStatus.state.selfConfigState.isError == True )

- name: show gateway details
  debug: 
    msg: "{{ gateway_current_status }}"
