---
- name: Converge
  hosts: all

  vars:
    # controller_fqdn: ""
    # api_key: ""
    # user_email: ""
    # user_password: ""
    #
    # environment_name: "production-us-west"
    # gateway:
    #   name: lending
    #   displayName: "Shared Public Lending BU Gateway"
    #   description: "Routes all non special Lending applications"
    #   tags:
    #     - production
    #     - us-west
    #     - lending
    # ingress:
    #   uris:
    #     - "http://mortgage.acmefinancial.net"
    #     - "https://mortgage.acmefinancial.net"
    #     - "http://ratecalculator.acmefinancial.net"
    #     - "https://ratecalculator.acmefinancial.net"
    #   tls:
    #     certRef:
    #       ref: "/services/environments/lending-prod/certs/star.acmefinancial.net"
    #     protocols:
    #       - "TLSv1.3"
    #       - "TLSv1.2"
    #   placement:
    #     instanceRefs:
    #       - "/infrastructure/locations/unspecified/instances/2"
    #       - "/infrastructure/locations/unspecified/instances/4"

  tasks:
    - include_role:
        name: ansible-role-nginx-controller-gateway
